clc;
clear all;
[poblacion, fitness, grafica]=binario(5000, 100, 1000);
disp("Poblacion");
disp(poblacion);
disp("Fitness");
disp(fitness);
hold on;
axis on;
title("Maximizar unos");
ylabel("Fitness");
xlabel("Iteraciones");
plot(grafica);